project:
  type: website

website:
  title: "Statistics"
  search: false
  navbar:
    logo: img/cropped-penang-institute-logo.png
    left:
      - about.qmd
    tools:
    - icon: house
      href: https://www.penanginstitute.org
  page-footer:
    left: "Copyright © Penang Institute"
    right: enquiry@penanginstitute.org
format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    # toc: true

editor: visual

