project:
  type: website
  preview: 
    port: 8080
    watch-inputs: true

metadata-files:
  - _website.yml

format:
  html:
    theme:
    - simplex
    - assets/custom.scss
    css: assets/styles.css
    page-layout: full
    # link-external-icon: true
    anchor-sections: false
    # toc: true
    html-math-method: plain

editor: visual

resources: 
- "keyPenangMetrics/output/*.yaml"