project:
  type: website

website:
  title: "Key Penang Statistics: Penang Institute"
  search: false
  navbar:
    title: Statistics
    logo: img/cropped-penang-institute-logo.png
    logo-alt: Penang Institute logo
    pinned: true
    left:
    - text: Penang at a glance
      href: '#penang-at-a-glance'
    - text: Dashboards
      href: '#dashboards'
    - text: New in Penang Monthly
      href: '#new-in-penang-monthly'
          # - text: Metadata
          #   href: https://hollow-locket-922.notion.site/552c1b91696141d48e9103522dc8ea01?v=fbeb4d0307514e1b9a7d12d2b284a436&pvs=4
          # - text: Data sources
          #   href: https://hollow-locket-922.notion.site/4079047156cf441398595107f688a30f?v=75577be15da545219fcaff695b4d7c96&pvs=4
    right:
    - text: Homepage
      icon: house
      href: https://www.penanginstitute.org
  page-footer:
    left: 
    - text: "Copyright © Penang Institute"
      href: "https://www.penanginstitute.org"
    right: 
    - text: Resources
      href: about.qmd   
  twitter-card:
    site: "@penanginstitute"
  open-graph:
    title: "Statistics at Penang Institute"
  google-analytics: "G-WTRQJLDY3E"
  repo-url: https://github.com/Penang-Institute/pistats
  repo-actions: [source]
format:
  html:
    theme:
    - simplex
    - custom.scss
    css: styles.css
    page-layout: full
    # toc: true

editor: visual

