project:
  type: website

website:
  title: "Statistics: Penang Institute"
  search: false
  navbar:
    title: Statistics
    logo: img/cropped-penang-institute-logo.png
    logo-alt: Penang Institute logo
    left:
      - about.qmd
    tools:
    - icon: house
      href: https://www.penanginstitute.org
  page-footer:
    left: "Copyright © Penang Institute"
    right: enquiry@penanginstitute.org
format:
  html:
    theme:
    - simplex
    - custom.scss
    css: styles.css
    page-layout: full
    # toc: true

editor: visual

